spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/bulk_graph_simple
    username: dbuser
    password: dbpass

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

  data:
    rest:
      base-path: /api

  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true

  sleuth:
    enabled: true
    propagation:
      type: B3,W3C,
    opentracing:
      enabled: true

  zipkin:
    base-url: http://simplest-collector.default.svc.cluster.local:9411

  cloud:
    compatibility-verifier:
      enabled: false

  application:
    name: timetable

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: always

  health:
    rabbit:
      enabled: true
    db:
      enabled: true

  info:
    git:
      enabled: true
      mode: full
    build:
      enabled: true

  server:
    port: 8081

logging:
  level:
    org.springframework: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.springframework.web.servlet: INFO
