spring:
  datasource:
    url: jdbc:h2:mem:db
    username: dbuser
    password: dbpass
    driverClassName: org.h2.Driver

  jpa:
    hibernate:

      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

  h2:
    console:
      enabled: true

  data:
    rest:
      base-path: /api

  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
#      path: /graphiql
#    path: /graphql

#  sleuth:
#    enabled: true
#    propagation:
#      type: B3,W3C,
#    opentracing:
#      enabled: true
#
#  zipkin:
#    base-url: http://simplest-collector.default.svc.cluster.local:9411

#  cloud:
#    compatibility-verifier:
#      enabled: false

  application:
    name: bulk-graph

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: always

  health:
    db:
      enabled: true

  info:
    git:
      enabled: true
      mode: full
    build:
      enabled: true

  server:
    port: 8081

logging:
  level:
    org.springframework: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.springframework.web.servlet: INFO
