version: "3.1"
services:

  # rabbit MQ
  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  # postgres DB
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: bulk
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
    ports:
      - 6831:6831/udp
      - 5775:5775/udp
      - 6832:6832/udp
      - 16686:16686
      - 5778:5778
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  postgres-data:
    driver: local
