openapi: 3.0.1
info:
  title: New Title
  description: "This is the Workspace service where one can create, update, get detail,\
    \ list and search for workspaces."
  version: 0.0.0-0-main
servers:
- url: http://localhost:8080
  description: localhost - 1
  variables: {}
- url: http://localhost:8081
  description: localhost - 2
  variables: {}
tags:
- name: commit
  description: e7062e9e586f15c9d672e27fc814fa047d405bbe
paths:
  /api/v1/workspaces:
    post:
      tags:
      - workspace-resource-impl
      description: blah blah
      operationId: createWorkspace
      parameters:
      - name: X-Subscriber-ID
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workspace'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WorkspaceResponse'
components:
  schemas:
    SecurityAddress:
      type: object
      properties:
        postcode:
          type: string
        name:
          type: string
        number:
          type: string
        flat:
          type: string
        street:
          type: string
        town:
          type: string
    Workspace:
      required:
      - mortgageApplicationReference
      type: object
      properties:
        transactionType:
          type: string
          enum:
          - REMORTGAGE
          - NEW_PURCHASE
        jurisdiction:
          type: string
          enum:
          - ENGLAND_WALES
        securityAddress:
          $ref: '#/components/schemas/SecurityAddress'
        mortgageApplicationReference:
          maxLength: 30
          minLength: 0
          type: string
    WorkspaceResponse:
      type: object
      properties:
        workspaceId:
          type: string
          format: uuid
