server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db
    username: dbuser
    password: dbpass

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

logging:
  level:
    org.org.springframework: debug
    org.bogerroad: debug
---

spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:db
    username: dbuser
    password: dbpass
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: pg

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bulk_trait
    username: dbuser
    password: dbpass

  flyway:
    enabled: true
