extraEnvVars:
  - name: SPRING_DATASOURCE_URL
    value: 'jdbc:postgresql://postgresql:5432/bulk-graph-simple'
  - name: SPRING_DATASOURCE_USERNAME
    value: 'postgres'
  - name: SPRING_DATASOURCE_PASSWORD
    value: 'postgres'
  - name: SPRING_ZIPKIN_BASE-URL
    value: 'http://simplest-collector.default.svc.cluster.local:9411'

springboot:
  profile: "dev"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
