apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      zipkin:
        endpoint: "0.0.0.0:9412"
      otlp:
        protocols:
          grpc:
    processors:
    exporters:
      logging:
        logLevel: debug
      jaeger:
        endpoint: "jaeger:14250"
        insecure: true
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"
        insecure: true
        format: json
    service:
      pipelines:
        traces:
          receivers:
            - otlp
            - zipkin
          processors:
          exporters:
            - logging
            - zipkin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel
  name: otel
spec:
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
      annotations:
        prometheus.io/scrape: 'false'
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - image:  otel/opentelemetry-collector:0.24.0
          imagePullPolicy: IfNotPresent
          name: otel
          ports:
            - containerPort: 4317
          args:
            - --config=/conf/collector.yaml
          volumeMounts:
            - mountPath: /conf
              name: collector-config
      volumes:
        - configMap:
            items:
              - key: collector.yaml
                path: collector.yaml
            name: collector-config
          name: collector-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel
  name: otel
spec:
  ports:
    - name: otel
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: zipkin
      protocol: TCP
      port: 9412
      targetPort: 9412
  selector:
    app: otel
