apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulk-backstage
  labels:
    app: bulk-backstage
spec:
  selector:
    matchLabels:
      app: bulk-backstage
  template:
    metadata:
      labels:
        app: bulk-backstage
    spec:
      containers:
      - name: bulk-backstage
        image: bulk-backstage
        ports:
        - containerPort: 7000
        env:
          - name: POSTGRES_HOST
            value: 'postgresql'
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_USER
            value: 'dbuser'
          - name: POSTGRES_PASSWORD
            value: 'dbpass'
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          - name: LOG_LEVEL
            value: debug
        envFrom:
          - secretRef:
              name: github
#        volumeMounts:
#          - mountPath: /var/run
#            name: docker-sock
      - name: dind-daemon
        image: docker:18.05-dind
        resources:
          requests:
            cpu: 20m
            memory: 512Mi
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-graph-storage
            mountPath: /var/lib/docker
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
#        - name: docker-sock
#          hostPath:
#            path: /var/run
#          - configMapRef:
#              name: ...
#          - configMapRef:
#              name: ...
