server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/bulk_multi_1
    username: dbuser
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
  quartz:
    job-store-type: jdbc
    auto-startup: true
    jdbc:
      initialize-schema: always
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://postgresql:5432/bulk_multi_2
      username: dbuser
      password: dbpass
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

#trigger:
#  name: Settlement Triggers
#  timezone: Europe/London
#  triggers:
#    - name: Slot 1
#      cron: '0 40 8 ? * MON-FRI'
##    - name: Slot 2
##      time: '08:40'
#    - name: Slot 3
#      cron: '0 28 15 ? * MON-FRI'
#    - name: Slot 4
#      cron: '0 29 15 ? * MON-FRI'
#    - name: Slot 5
#      cron: '0 30 15 ? * MON-FRI'
#    - name: Slot 6
#      cron: '0 * * * * ?'

logging:
  level:
    org.quartz: DEBUG
