spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        emailMessageConsumer-in-0:
          destination: topic1
        emailTemplateConsumer-in-0:
          destination: topic2
      function:
        definition: emailMessageConsumer;emailTemplateConsumer

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
      show-details: always
  health:
    db:
      enabled: true
  info:
    git:
      mode: simple

logging:
  level:
    root: INFO
    org.apache.kafka: WARN

