server:
  port: 8080

grpc:
  enableReflection: true
  port: 6565

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/bulk_plan_api
    username: dbuser
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
  rabbitmq:
    username: guest
    password: guest
    addresses: amqp://rabbitmq:5672
    template:
      exchange: planning
      routing-key: create
